### ISSUE TITLE
如果添加svg的图形是白色，能否有一种反白的展示效果或者是底色灰点让白色的图形能展现出来

### ISSUE THREAD

**Issue by SMWL-0001** [bytedance/IconPark#222]
如果添加svg的图形是白色，能否有一种反白的展示效果或者是底色灰点让白色的图形能展现出来

**Comment by SMWL-0001** [comment]
设计师

**Comment by AppleMonkey2019** [comment]
@qifengfei 帮忙看看~

**Comment by davinma** [comment]
目前我是通过浏览器插件自定义样式的方式，临时让它看起来更明显一些：

```css
.styles_iconList .styles_iconCard {
    margin: 8px;
    position: relative;
    background-image: repeating-linear-gradient(45deg, #e6e6e6 25%, transparent 25%, transparent 75%, #e6e6e6 75%, #e6e6e6), repeating-linear-gradient(45deg, #e6e6e6 25%, #ffffff 25%, #ffffff 75%, #e6e6e6 75%, #e6e6e6);
    background-position: 0 0, 10px 10px;
    background-size: 20px 20px;
}
```

预览效果图：

<img width="334" alt="image" src="https://user-images.githubusercontent.com/2345776/176374994-d5465132-d4a0-4b72-b311-a63027a52a92.png">
